export enum Category {
  Food = "Food",
  Housing = "Housing",
  Utilities = "Utilities",
  Transport = "Transport",
  Entertainment = "Entertainment",
  Salary = "Salary",
  Other = "Other",
  Healthcare = "Healthcare",
  Education = "Education",
  Shopping = "Shopping",
  Travel = "Travel",
  Insurance = "Insurance",
  Subscriptions = "Subscriptions",
}
